title: CaseStudy2
description: Project website using Just the Docs template
theme: just-the-docs

url: https://github.com/torih1541/CaseStudy2DDS

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
